---
- include: zookeeper.yml
  tags:
  - zookeeper

- include: exhibitor.yml
  tags:
  - exhibitor

- name: Ensure exhibitor service running
  service: >
    name=exhibitor
    state=started
    enabled=yes
